# Generated by Django 4.2.11 on 2024-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaofinanceira',
            name='idpagaritem',
        ),
        migrations.RemoveField(
            model_name='movimentacaofinanceira',
            name='idreceberitem',
        ),
        migrations.RemoveField(
            model_name='movimentacaofinanceira',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='movimentacaoprodutos',
            name='Idprodutodetalhe',
        ),
        migrations.RemoveField(
            model_name='movimentacaoprodutos',
            name='idcompraitem',
        ),
        migrations.RemoveField(
            model_name='movimentacaoprodutos',
            name='idproduto',
        ),
        migrations.RemoveField(
            model_name='movimentacaoprodutos',
            name='idvendaitem',
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='TipoFluxo',
            field=models.CharField(default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='TipoMov',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='Titulo',
            field=models.CharField(default='00000000-0', max_length=10),
        ),
        migrations.AddField(
            model_name='movimentacaoprodutos',
            name='CodigodeBarra',
            field=models.CharField(default='0000000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='movimentacaoprodutos',
            name='codigoproduto',
            field=models.CharField(default='00.00.00000', max_length=11),
        ),
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='data_baixa',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='movimentacaoprodutos',
            name='Documento',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaoprodutos',
            name='Tipo',
            field=models.CharField(default='V', max_length=1),
        ),
    ]
