# Generated by Django 4.2.11 on 2024-06-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='categoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
