# Generated by Django 4.2.11 on 2024-08-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0002_remove_movimentacaofinanceira_idpagaritem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='data_baixa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
