# Generated by Django 4.2.11 on 2024-06-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0003_grupo_material_subgrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='produto_foto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
