# Generated by Django 4.2.11 on 2024-08-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0003_alter_movimentacaofinanceira_data_baixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='meta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
