# Generated by Django 4.2.11 on 2024-06-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0004_alter_produto_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_foto1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='produto_foto2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
