# Generated by Django 4.2.11 on 2024-08-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0005_despesa_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caixa',
            name='status',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='caixa',
            name='usuario',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
