# Generated by Django 4.2.11 on 2024-06-20 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0005_produto_produto_foto1_produto_produto_foto2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('Idcolecao', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=10)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('Idfamilia', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ncm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=20)),
                ('campo1', models.CharField(blank=True, max_length=25, null=True)),
                ('descricao', models.CharField(max_length=1000)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('Idunidade', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
