# Generated by Django 4.2.11 on 2024-06-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0006_colecao_familia_ncm_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='aliquota',
            field=models.CharField(max_length=20),
        ),
    ]
