# Generated by Django 4.2.11 on 2024-06-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0007_alter_ncm_aliquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='Codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
