# Generated by Django 4.2.11 on 2024-06-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0008_unidade_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='Codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='Codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='Codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='Status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='Status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
