# Generated by Django 4.2.11 on 2024-06-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0009_colecao_codigo_familia_codigo_material_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cor',
            name='Codigo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='cor',
            name='Status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tamanho',
            name='Status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
