# Generated by Django 4.2.11 on 2024-06-21 02:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0010_cor_codigo_cor_status_tamanho_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('Idgrade', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='tamanho',
            name='Descricao',
        ),
        migrations.AddField(
            model_name='tamanho',
            name='idgrade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='systakapp.grade'),
            preserve_default=False,
        ),
    ]
