# Generated by Django 4.2.11 on 2024-06-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0012_produtodetalhe_codigoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='referencia',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
