# Generated by Django 4.2.11 on 2024-06-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0014_alter_produto_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='referencia',
            field=models.CharField(default='00.00.00000', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='produtodetalhe',
            name='CodigodeBarra',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='produtodetalhe',
            name='Codigoproduto',
            field=models.CharField(default='000000', max_length=6, unique=True),
        ),
    ]
