# Generated by Django 4.2.11 on 2024-06-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0015_alter_produto_referencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiposdesubgrupo',
            fields=[
                ('Idtipodesubgrupo', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('codigosubgrupo', models.CharField(max_length=2)),
            ],
        ),
    ]
