# Generated by Django 4.2.11 on 2024-06-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0016_tiposdesubgrupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgrupo',
            name='idgrupo',
        ),
        migrations.DeleteModel(
            name='Tiposdesubgrupo',
        ),
        migrations.DeleteModel(
            name='Subgrupo',
        ),
    ]
