# Generated by Django 4.2.11 on 2024-06-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0018_subgrupo_grupodetalhe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('Idcodigo', models.AutoField(primary_key=True, serialize=False)),
                ('variavel', models.CharField(max_length=15)),
                ('valor', models.IntegerField()),
                ('contador', models.IntegerField()),
            ],
        ),
    ]
