# Generated by Django 4.2.11 on 2024-06-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0019_codigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='Estacao',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='Codigo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
