# Generated by Django 4.2.11 on 2024-06-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0020_colecao_estacao_alter_colecao_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='referencia',
            field=models.CharField(default='000.00.00000', max_length=12, unique=True),
        ),
    ]
