# Generated by Django 4.2.11 on 2024-06-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0021_alter_produto_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='Estacao',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
