# Generated by Django 4.2.11 on 2024-06-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0022_alter_colecao_estacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='referencia',
            field=models.CharField(default='00.00.00000', max_length=11, unique=True),
        ),
    ]
