# Generated by Django 4.2.11 on 2024-06-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0023_alter_produto_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='Contador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
