# Generated by Django 4.2.11 on 2024-06-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0024_colecao_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='Contador',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
