# Generated by Django 4.2.11 on 2024-07-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0026_alter_produtodetalhe_codigoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtodetalhe',
            name='Item',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
