# Generated by Django 4.2.11 on 2024-07-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0027_produtodetalhe_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigos',
            name='contador',
        ),
    ]
