# Generated by Django 4.2.11 on 2024-07-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0028_remove_codigos_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='valor',
            field=models.CharField(max_length=15),
        ),
    ]
