# Generated by Django 4.2.11 on 2024-07-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0029_alter_codigos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='variavel',
            field=models.CharField(max_length=7),
        ),
    ]
