# Generated by Django 4.2.11 on 2024-07-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0032_rename_data_tabelapreco_datafim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelapreco',
            name='NomeTabela',
            field=models.CharField(default='Tabela', max_length=100),
        ),
    ]
