# Generated by Django 4.2.11 on 2024-07-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0033_tabelapreco_nometabela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelapreco',
            name='Promocao',
            field=models.CharField(max_length=3),
        ),
    ]
