# Generated by Django 4.2.11 on 2024-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0034_alter_tabelapreco_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='codigoproduto',
            field=models.CharField(default='00.00.00000', max_length=11),
        ),
    ]
