# Generated by Django 4.2.11 on 2024-07-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0035_estoque_codigoproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='Idprodutodetalhe',
        ),
    ]
