# Generated by Django 4.2.11 on 2024-07-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0036_remove_estoque_idprodutodetalhe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaitem',
            name='Idproduto',
        ),
        migrations.RemoveField(
            model_name='vendaitem',
            name='Idprodutodetalhe',
        ),
        migrations.RemoveField(
            model_name='vendaitem',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='CodigodeBarra',
            field=models.CharField(default='0000000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='codigoproduto',
            field=models.CharField(default='00.00.00000', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Caixa', 'Caixa'), ('Gerente', 'Gerente'), ('Admin', 'Admin')], default='Regular', max_length=10),
        ),
    ]
