# Generated by Django 4.2.11 on 2024-07-20 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0037_remove_vendaitem_idproduto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='Data_entrega',
            new_name='Data_venda',
        ),
        migrations.AlterField(
            model_name='venda',
            name='Data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
