# Generated by Django 4.2.11 on 2024-07-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0038_rename_data_entrega_venda_data_venda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='data_cadastro',
        ),
    ]
