# Generated by Django 4.2.11 on 2024-07-20 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0039_remove_venda_data_cadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigos',
            old_name='valor',
            new_name='valor_var',
        ),
    ]
