# Generated by Django 4.2.11 on 2024-07-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0040_rename_valor_codigos_valor_var'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaitem',
            name='Documento',
            field=models.CharField(default='', max_length=20),
        ),
    ]
