# Generated by Django 4.2.11 on 2024-07-23 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0041_vendaitem_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='idfuncionario',
        ),
        migrations.AddField(
            model_name='venda',
            name='Idvendedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='systakapp.vendedor'),
        ),
    ]
