# Generated by Django 4.2.11 on 2024-07-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0042_remove_venda_idfuncionario_venda_idvendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaitem',
            name='Idvenda',
        ),
    ]
