# Generated by Django 4.2.11 on 2024-07-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0044_remove_venda_data_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='Idvendedor',
        ),
        migrations.AddField(
            model_name='venda',
            name='Idfuncionario',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='systakapp.funcionarios'),
        ),
    ]
