# Generated by Django 4.2.11 on 2024-07-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0047_receberitens_parcela_receberitens_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receber',
            name='Titulo',
        ),
        migrations.AlterField(
            model_name='receberitens',
            name='Titulo',
            field=models.CharField(default='00000000-0', max_length=10),
        ),
    ]
