# Generated by Django 4.2.11 on 2024-07-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0049_alter_receberitens_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='acrescimo',
            field=models.DecimalField(decimal_places=5, max_digits=18),
        ),
        migrations.AlterField(
            model_name='venda',
            name='comissao',
            field=models.DecimalField(decimal_places=5, max_digits=18),
        ),
    ]
