# Generated by Django 4.2.11 on 2024-08-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0051_imposto_recebercartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imposto',
            name='idloja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='systakapp.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='tcofins',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='venda',
            name='tcsll',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='venda',
            name='ticms',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='venda',
            name='tpis',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='icofins',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='icsll',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='iicms',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='ipis',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
    ]
