# Generated by Django 4.2.11 on 2024-08-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systakapp', '0052_imposto_idloja_venda_tcofins_venda_tcsll_venda_ticms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receber',
            name='TipoRecebimento',
        ),
    ]
